export const SET_PULL_REQUEST_DATA = 'SET_PULL_REQUEST_DATA'
export const SET_PULL_REQUEST_DATA_LOADING_STATUS = 'SET_PULL_REQUEST_DATA_LOADING_STATUS'
export const SET_PULL_REQUEST_DATA_LOADING_ERROR_STATUS = 'SET_PULL_REQUEST_DATA_LOADING_ERROR_STATUS'

export const SET_PROFILE_DATA = 'SET_PROFILE_DATA'
export const SET_PROFILE_DATA_LOADING_STATUS = 'SET_PROFILE_DATA_LOADING_STATUS'
export const SET_PROFILE_DATA_LOADING_ERROR_STATUS = 'SET_PROFILE_DATA_LOADING_ERROR_STATUS'

export const SET_REPOSITORY_DATA = 'SET_REPOSITORY_DATA'
export const SET_REPOSITORY_DATA_LOADING_STATUS = 'SET_REPOSITORY_DATA_LOADING_STATUS'
export const SET_REPOSITORY_DATA_LOADING_ERROR_STATUS = 'SET_REPOSITORY_DATA_LOADING_ERROR_STATUS'
