export const SET_PROFILE_DATA = 'SET_PROFILE_DATA'
export const SET_PROFILE_DATA_LOADING_STATUS = 'SET_PROFILE_DATA_LOADING_STATUS'
export const SET_PROFILE_DATA_LOADING_ERROR_STATUS = 'SET_PROFILE_DATA_LOADING_ERROR_STATUS'
